### PR TITLE
Update from latest skeleton

### PR DESCRIPTION
**Pull request by dav3r**
# 

## 🗣 Description
This PR pulls in the latest updates from [`skeleton-ansible-role`](https://github.com/cisagov/skeleton-ansible-role).

## 💭 Motivation and Context
I am preparing to make some additional updates to this repo and I wanted to make sure it was up-to-date with the skeleton before making further changes.
 

## 🧪 Testing
I ran `molecule test` and verified that there were no failures.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dav3r** [comment]
I'm troubleshooting now to figure out why the `molecule` tests ran fine on my local machine, but they are failing when GitHub Actions run them.

**Review by jsf9k — APPROVED** [review]
This looks good to me. :star2:

**Review by mcdonnnj — APPROVED** [review]
Modern. ✨

**Review by felddy — APPROVED** [review]
💀 Looks... good. 💀

**Pull request merged**
