### PR TITLE
Add a comment explaining why we are using passwordless sudo.

### LINKED ISSUE #21: Why is sudo NOPASSWD option set for wheel group?
Why, of all Gov't agencies, CISA should be last agency to push passwordless sudo-ing.

### PR DESCRIPTION
**Pull request by felddy**
Be a bit more clear about why we are configuring sudo to allow escalation without a password. 

This closes #21.

#  #

## 🗣 Description ##

A concern was raised that we are endorsing the use of sudo without passwords.  This PR contains a comment
which adds additional context.

## 💭 Motivation and context ##

This PR clarifies why we are configuring sudo this way so it is not confused as a general endorsement as a best practice.

## 🧪 Testing ##

I read the comment, and thought it was good.

## 📷 Screenshots (if appropriate) ##

tenor-2

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [ ] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 
Is this PR failing because of the issue in https://github.com/cisagov/skeleton-ansible-role/issues/69?

**Comment by mcdonnnj** [comment]
> 
> 
> 👍
> Is this PR failing because of the issue in [cisagov/skeleton-ansible-role#69](https://github.com/cisagov/skeleton-ansible-role/issues/69)?

Looking at the logs, yes, that appears to be the case.

**Review by mcdonnnj — APPROVED** [review]
📜

**Review by hillaryj — APPROVED** [review]
#️⃣

**Pull request merged**
